### ISSUE TITLE
Chap 6 MongoDB Node.js Driver - Cleaning up the collection before test failed p.157

### ISSUE THREAD

**Issue by thomascarpenter21** [vasansr/pro-mern-stack-2#10]
Hello, 
Im having trouble "cleaning up the collection before test". I've tried the following:
1.  mongo issuetracker --eval "db.employees.removed({})" 
  1a.  error message [js] uncaught exception: SyntaxError: unexpected token: identifier :
@(shell):1:6
2. mongo mongodb+srv://cluster0-IssueTrackerMERN.mongodb.net/issuetracker --USERNAME atlasUser --PASSWORD atlasPassword --eval "db.employees.remove({})"
   2a.Error message: [js] uncaught exception: SyntaxError: unexpected token: string literal :
@(shell):1:6
3. mongo "mongodb+srv://issuetrackermern-kut6p.mongodb.net/test" --username USERNAME --password PASSWORD --eval "db.employees.remove({})"
    3a. Error message: [js] uncaught exception: SyntaxError: unexpected token: identifier :
@(shell):1:6
   3b. the above code is the connection string from MongoDB.

Im stuck. Any direction would be helpful. 
Thank you,
Thomas

**Comment by vasansr** [comment]
Hey, you are expected to run these from the OS shell (command line), and not from within the Mongo shell.

If you are already within the Mongo shell, just a simple db.employees.remove({}) will do the needful.

**Comment by thomascarpenter21** [comment]
Hey, thanks for the tip. Ran db.employees.remove({}) in Mongo shell and it returned in shell WriteResult({ "nRemoved" : 0}).  Then ran node scripts/trymongo.js in Mongo shell and got error message uncaught exception: syntaxError: unexpected token: identifier: @(shell): 1:5. 
Please help.
Thomas
