### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by siricoa94** [vasansr/pro-mern-stack-2#14]
Not sure where my problem is, attached 
here is a screenshot of my server.js file and my package.json.\
![Screenshot (31)](https://user-images.githubusercontent.com/50495407/87471473-6a9f4d00-c5ec-11ea-88f2-c1f3a4bc141c.png)
![Screenshot (30)](https://user-images.githubusercontent.com/50495407/87471478-6d01a700-c5ec-11ea-8ebb-1abb9ea8d2b5.png)

**Comment by siricoa94** [comment]
fixed with
"npm install --save graphql@14.2.1".

**Comment by Ezra-Siton-UIX** [comment]
Same error (The current version is: 15.3.0 - maybe this is some conflict). The code above fixes my issue too. Thanks!

**Comment by mayhs19** [comment]
> fixed with
> "npm install --save graphql@14.2.1".

This helped me as well !
