### ISSUE TITLE
$ mongo issuetracker scripts/init.mongo.js

### ISSUE THREAD

**Issue by siricoa94** [vasansr/pro-mern-stack-2#15]
So I am having a problem with running this command in my terminal. When I type this directly into my terminal it returns saying "bash: mongo: command not found". I also tried typing this into my mongo shell to no avail. I am not quite sure what may be wrong but I will include some screen shots here of what my shells are returning. Also, I have mongodb version 3.5.9 installed in my package.json with 4.2 being the version on my machine which is located within my program files directory in my C drive.

**Mongo Shell**:
![commandPrompt](https://user-images.githubusercontent.com/50495407/88252326-c0729580-cc7b-11ea-9ade-f3c2acf32af8.png)

**Command Prompt**
![mongoShell](https://user-images.githubusercontent.com/50495407/88252327-c0729580-cc7b-11ea-9eb5-324a3a260080.png)

**Terminal**
![terminal](https://user-images.githubusercontent.com/50495407/88252328-c0729580-cc7b-11ea-997c-866dd7d9b607.png)

**Comment by siricoa94** [comment]
I believe I was in the wrong directory, here is a screenshot of my command prompt to show the directory. Furthermore, you also may want to make sure you have environment variables properly set for your mongoDB bin.
![Screenshot (38)](https://user-images.githubusercontent.com/50495407/88330051-d2dee480-ccf8-11ea-8b69-653a17ea5df4.png)

**Comment by albionferracakuagic** [comment]
If anyone else has this problem. 
Solution for me: adding mongo.exe file to system32 folder.
