### ISSUE TITLE
GET http://localhost:8000/index.js net::ERR_ABORTED 404 (not found)

### ISSUE THREAD

**Issue by mikekmcd** [vasansr/pro-mern-stack-2#22]
Since making changes beginning in Chapter 7 (Architecture and ESLint) i have been having problems getting the ui to load in the browser. Initially i was getting 'unexpected token < in JSON at position 0' (after creating separate ui and api servers). Then failing to fix this i continued with the chapter hoping more changes might resolve the issue. Now i have completed everything up to and including Ch7 Proxy-Based-Architecture. The ui will still not load in the browser and i'm getting the above (404) error. Everything else appears to be working fine: both servers are running in the terminal and the graphql playground is loading fine.

The code should be fine as i've even gone over it and even copied and pasted from this Git repository just to be double sure. I've also checked the file structure. The only difference is my package.json, as due to dependancy issues i've encountered, some of the package versions are different, so i'm wondering if this could be the problem. But it is unclear to me as i'm getting no issues in the terminal when i run the servers.

{
  "name": "pro-mern-stack-2-ui",
  "version": "1.0.0",
  "description": "Pro MERN Stack (2nd Edition) - UI",
  "main": "index.js",
  "scripts": {
    "start": "nodemon -w uiserver.js -w .env uiserver.js",
    "compile": "babel src --out-dir public",
    "watch": "babel src --out-dir public --watch --verbose"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/vasansr/pro-mern-stack-2.git"
  },
  "author": "vasan.promern@gmail.com",
  "license": "ISC",
  "homepage": "https://github.com/vasansr/pro-mern-stack-2",
  "dependencies": {
    "dotenv": "^6.2.0",
    "express": "^4.16.4",
    "http-proxy-middleware": "^0.21.0",
    "nodemon": "^1.18.9"
  },
  "devDependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.2.2",
    "@babel/preset-env": "^7.2.3",
    "@babel/preset-react": "^7.0.0"
  }
}

**Comment by petelc** [comment]
what does your google dev tools show you? I ran into the same 'unexpected token < in JSON at position 0' issue and if i remember correctly the jsonDateReviver never worked for me and caused me all sorts of head aches so I removed it from the process. But this error is what is causing your issue (at least in my opinion) I googled it and tried a lot of "fixes" this I got what worked for me.

**Comment by mikekmcd** [comment]
<img width="1048" alt="Screenshot 2020-08-16 at 08 20 24" src="https://user-images.githubusercontent.com/60618312/90329344-f0236d80-df9b-11ea-8dbe-feb3028b5502.png">

**Comment by mikekmcd** [comment]
At the start of Ch7 i was getting the 'unexpected token < in JSON at position 0' error, like i mentioned i just carried on working through the material after being unable to fix it. Eventually i stopped seeing that error, but it made little difference as the ui is still not loading in the browser and i'm getting the above errors.

I tried removing the jsonDateReviver as you suggested. I removed the following code, which as the first 6 lines of my current App.jsx (if i have understood this correctly?)

```
const dateRegex = new RegExp('^\\d\\d\\d\\d-\\d\\d-\\d\\d');

function jsonDateReviver(key, value) {
  if (dateRegex.test(value)) return new Date(value);
  return value;
}
```

However, i'm still getting the same error as above in dev tools.

**Comment by petelc** [comment]
So I am further along in the book and he does some refactoring but when you comment out the above you also need to remove the reference to it ( I assume you know that) here is part of my graphQLFetch

`  method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ query, variables }),
    });
    const body = await response.text();
    const result = JSON.parse(body);`

so in the dev tools you have it on networking but click the console tab 

![image](https://user-images.githubusercontent.com/8117503/90329948-171b7880-df77-11ea-919f-43f9dd6db836.png)

Are there any errors there? And are you compiling the code with npm run watch (I think that is the command)

**Comment by mikekmcd** [comment]
Ok i got it working, thanks. It may have been as simple as i hadn't run the npm run watch command to compile the ui server, glad you suggested that. I was doing that all along upto now but for some reason i had the understanding that i just needed npm start to get both servers going.

FYI it is working ok with the jsonDateReviver and all code as it was (actually, i hadn't removed the reference to it in the graphQLFetch function, so if that had been the issue i would have needed that). And no errors in dev tools/console now.

**Comment by petelc** [comment]
Great! I still have not got the dates to format correctly. I got frustrated with it and worked around it. I even created an issue here but no response. Glad you got it working.

**Comment by mikekmcd** [comment]
I had a look at your question. It may be nothing but i just scanned through the code in your question and towards the end of your App.jsx i noticed there seem to be some back ticks missing (unless this is a later amendment, i'm on Ch7). This is the code as i have it:

```
async loadData() {
    const query = `query {
      issueList {
        id title status owner
        created effort due
      }
    }`;
```

**Comment by petelc** [comment]
So that's a real kicker! Thank you for pointing that out. It is working now. I am in Chapter 11 and I have been looking at that since it was first done.

**Comment by mikekmcd** [comment]
Brilliant!
