### ISSUE TITLE
Unorganized commit history

### ISSUE THREAD

**Issue by mr-correct** [vasansr/pro-mern-stack-2#23]
You wrote to refer to your repository for the correct code, but I can't find the completed/finished versions for each chapter and section. I recommend making git repository again to show clear code changes over sections of the book.

**Comment by petelc** [comment]
So if you are on the master branch of his repository and you scroll down you will see the entire book broken down to chapters and then those broken down to sections of the chapter and you can access either the full code or just the changes.

**Comment by vasansr** [comment]
That is correct, thank you @petelc . @mr-correct , please scroll down in this page: https://github.com/vasansr/pro-mern-stack-2 and you will find links to the source at the end of each section as also the diffs from the previous section.

**Comment by mr-correct** [comment]
Hi, let me explain further. Of course, I see the commit history. But please take a look at the attached picture. That's what I want to say.
![Screenshot_125](https://user-images.githubusercontent.com/62521461/90363501-75d71400-e095-11ea-8882-871cc19a12d6.png)
