### ISSUE TITLE
Unorganized commit history-2

### ISSUE THREAD

**Issue by mr-correct** [vasansr/pro-mern-stack-2#24]
Hi, let me explain further. Of course, I see the commit history. But please take a look at the attached picture. That's what I want to say.
![Screenshot_125](https://user-images.githubusercontent.com/62521461/90363501-75d71400-e095-11ea-8882-871cc19a12d6.png)

_Originally posted by @mr-correct in https://github.com/vasansr/pro-mern-stack-2/issues/23#issuecomment-674685284_

**Comment by petelc** [comment]
![image](https://user-images.githubusercontent.com/8117503/90369081-1d722900-e039-11ea-8e75-03a08e611645.png)

those 2 branches have the full code that is up to the end of that section.

**Comment by vasansr** [comment]
Also, if you'd rather use git on your local repository, you can diff the two branches 05.06-create-api and 05.07-integrate-create-api. I am sure Tortoise will give you an ability to do this as well, but the git command line for the same is:

`git diff 05.06-create-api 05.07-integrate-create-api`
