### ISSUE TITLE
Chapter 14 - Cookie Domain

### ISSUE THREAD

**Issue by siricoa94** [vasansr/pro-mern-stack-2#28]
In this section of the chapter you say to create a domain and two sub domains, both of which point to localhost. You say this can be done by editing the hosts file and adding the following line: "127.0.0.1 api.promernstack.com ui.promernstack.com". Should I add this above my current "127.0.0.1 localhost"? or should it go below? Also, how will this change affect future development on my machine?

Also, how should this file be opened and saved. When opening "c:\Windows\System32\Drivers\etc\hosts", I opened it as a text document, should I also save it as a text document in the same directory?

Furthermore, I am not permitted by my machine to save a text file in that directory, I have not attempted to do so yet with administrator privileges.

I closed this issue thinking I was not logged in as administrator, which I was. So windows still does not grant me access to edit/save the hosts file in the same directory.

**Comment by siricoa94** [comment]
So if anyone has any idea how to open, where to make the changes, and how to save this file, and in which directory to save it in would be really useful information as it is not provided in the text. I hope this is not an issue that goes unanswered for I would really like to cover this feature before moving forward. As a note to the author's, please be very specific with what you are doing. This is a pretty big deal that you do not even explain which directory to save it in. As a reader, I never mind having more text to read, what I do mind is a lack of information for the sake of brevity.

**Comment by vasansr** [comment]
1. The lines can be added anywhere, above or below. It does not matter
2. Yes, the same file has to be overwritten. Edit and save it as a text document.
3. You would need Administrator privileges. How to get this would depend on the version of Windows you are on.
4. The effect of this change is that you are "hardcoding" what these domain names point to. If ever there is a real website called any of these domain names, they would not work as expected, unless you remove these lines. (Windows looks at this file before making a query to a DNS server for the IP address of any website.)

This file is a common one and managed by windows. Unfortunately, I am not a user of the Windows OS and I do not have the details of how different flavours of Windows behave in terms of Admin privileges. Information on the internet will be more reliable than whatever I can provide here. Please search for this info, for example: "How to edit hosts file on windows 10", if your OS version is indeed Windows 10.

Thanks for your feedback regarding the details that a reader usually expects. My bad.

**Comment by siricoa94** [comment]
Thank you for responding and I would like to apologize. Even when signed in as Administrator on windows, I could not edit the file. To solve this problem I gave Users full control in order to edit/save the file. After doing this it no longer prompted me to save as a specific file type and allowed me to make changes in the same directory. I am still unsure as to why I was unable to make these changes as Administrator, but this solution worked for now.
