### ISSUE TITLE
[GraphQLError: Cannot destructure property `issue` of 'undefined' or 'null'.]

### ISSUE THREAD

**Issue by openmymai** [vasansr/pro-mern-stack-2#3]
Thank you very much, Master Vasan.
Since I know you have release 2nd edition, then I buy it with Kindle reading.

So cannot wait for trying to do the lab.
I try to start from GraphQL and MongoDB Chapter 6.
It works very well to display but when I add, I get the following error.
[GraphQLError: Cannot destructure property `issue` of 'undefined' or 'null'.]

**Comment by vasansr** [comment]
It looks like there are no records for GraphQL to destructure. Did you populate the database with a few issues? You could use the script init.mongo.js to do this.

**Comment by tmintner** [comment]
The code for issueVailidate isn't quite correct.  It should be:
function issueValidate(issue) {

**Comment by vasansr** [comment]
Yes, absolutely. Thanks @tmintner. I will make the correction.

(I think the previous chapter had it correct and some incorrect merges have broken it in the last section of MongoDB, Chapter 6).

**Comment by vasansr** [comment]
Fixed, made the changes all the way up to 07.06. Chapter 8 onwards the files are reorganized, they won't need this fix.
