### ISSUE TITLE
[Not an issue! Request to delete]Chapter 7.02 localhost:8000 says Error in sending data to server: Failed to fetch

### ISSUE THREAD

**Issue by albionferracakuagic** [vasansr/pro-mern-stack-2#39]
![image](https://user-images.githubusercontent.com/58115200/111474488-6bb0ed00-872c-11eb-8d1e-c261c4bc70ae.png)
As you can see on the image I was having problems with cors privacy. 

Solution: editing env.js file

File content described in book:
    window.ENV = {
        UI_API_ENDPOINT: "http://localhost:3000"
    }

Edited:
    window.ENV = {
        UI_API_ENDPOINT: "http://localhost:3000/graphql"
    }

**Comment by albionferracakuagic** [comment]
I have misunderstood this section and made inappropriate changes to my project.

**Comment by Hitendra27** [comment]
Thank You albiCoder.
I had the same issue and your solution worked for me.
