### ISSUE TITLE
CH 3 React Classes: message is not defined in App.js

### ISSUE THREAD

**Issue by thomascarpenter21** [vasansr/pro-mern-stack-2#9]
I getting the message "Uncaught ReferenceError: message is not defined at App.js:4"

In Index.html I have "<script src="App.js"></script>". In App.js I have 
"const element = /*#__PURE__*/React.createElement("div", {
  title: "Outer div"
}, /*#__PURE__*/React.createElement("h1", null, message));
ReactDOM.render(element, document.getElementById('contents'));"

Nothing is rendered to the UI. Do i need to add the public/app.js to the a .gitignore file? 
Thanks!

**Comment by vasan-agrostar** [comment]
Which chapter/page are you at?

**Comment by vasansr** [comment]
Chapter 3: By now you should have moved to JSX. Please check against the code in the corresponding branch: https://github.com/vasansr/pro-mern-stack-2/tree/03.01-react-classes
